### ISSUE TITLE
how to run ?

### ISSUE THREAD

**Issue by MohamedWn** [ANDRVV/gapcast#1]
──(root㉿kali)-[/]
└─# cd gapcast

┌──(root㉿kali)-[/gapcast]
└─# go build -buildvcs=false
# github.com/google/gopacket/pcap
/root/go/pkg/mod/github.com/google/gopacket@v1.1.19/pcap/pcap_unix.go:34:10: fatal error: pcap.h: No such file or directory
   34 | #include <pcap.h>
      |          ^~~~~~~~
compilation terminated.

┌──(root㉿kali)-[/gapcast]
└─# ./gapcast -i wlan1
zsh: no such file or directory: ./gapcast

┌──(root㉿kali)-[/gapcast]
└─# ls                                                                                                      config           database  gapcast.go  go.sum  libs     log        SECURITY.md
CONTRIBUTING.md  EvilTwin  go.mod      images  LICENSE  README.md

┌──(root㉿kali)-[/gapcast]
└─#

**Comment by ANDRVV** [comment]
Hi,

before you compile `gapcast.go`, you **must** install the _pcap library_.

To install _pcap library_:
`apt install libpcap-dev`

Now, you can compile and run.
Update me if it works.

**Comment by MohamedWn** [comment]
> Hi,
> 
> before you compile `gapcast.go`, you **must** install the _pcap library_.
> 
> To install _pcap library_: `apt install libpcap`
> 
> Now, you can compile and run. Update me if it works.

THX . WORKS NOW
